-- =========================================
-- PROJETO: SISTEMA BANCÁRIO AULA SQL (ORACLE)
-- Autor: Miguel Roberto
-- =========================================

-- Remover tabelas existentes
DROP TABLE CONTA_CORRENTE CASCADE CONSTRAINTS;
DROP TABLE AGENCIA CASCADE CONSTRAINTS;
DROP TABLE BANCO CASCADE CONSTRAINTS;

-- =========================================
-- TABELA BANCO
-- =========================================
CREATE TABLE BANCO (
    COD_BANCO NUMBER(3) NOT NULL,
    CNPJ NUMBER(15) NOT NULL,
    RAZAO_SOCIAL VARCHAR2(60) NOT NULL,
    NOME_FANTASIA VARCHAR2(60),
    DATA_ABERTURA DATE NOT NULL,
    DATA_FECHAMENTO DATE,
    LOGRADOURO VARCHAR2(60) NOT NULL,

    CONSTRAINT BANCO_PK PRIMARY KEY (COD_BANCO)
);

COMMENT ON TABLE BANCO IS
'Tabela responsável por armazenar informações cadastrais das instituições financeiras';

INSERT INTO BANCO VALUES
(001, 33456789000191, 'BANCO DO BRASIL S.A.', 'Banco do Brasil',
TO_DATE('12/10/1808','DD/MM/YYYY'), NULL, 'Setor Bancário Sul, Brasília');

INSERT INTO BANCO VALUES
(341, 45678912345678, 'ITAÚ UNIBANCO HOLDING S.A.', 'Itaú',
TO_DATE('03/11/1924','DD/MM/YYYY'), NULL, 'Avenida Paulista, São Paulo');

INSERT INTO BANCO VALUES
(237, 98765432100015, 'BANCO BRADESCO S.A.', 'Bradesco',
TO_DATE('10/03/1943','DD/MM/YYYY'), NULL, 'Cidade de Deus, Osasco');

-- =========================================
-- TABELA AGENCIA
-- =========================================
CREATE TABLE AGENCIA (
    COD_BANCO NUMBER(3) NOT NULL,
    COD_AGENCIA NUMBER(5) NOT NULL,
    NOME_AGENCIA VARCHAR2(60) NOT NULL,
    LOGRADOURO VARCHAR2(60) NOT NULL,

    CONSTRAINT AGENCIA_PK PRIMARY KEY (COD_BANCO, COD_AGENCIA),
    CONSTRAINT AGENCIA_BANCO_FK FOREIGN KEY (COD_BANCO)
        REFERENCES BANCO(COD_BANCO)
);

INSERT INTO AGENCIA VALUES
(001, 1001, 'Agência Central Brasília', 'Setor Bancário Sul, Quadra 1, Brasília');

INSERT INTO AGENCIA VALUES
(001, 1002, 'Agência Asa Norte', 'Asa Norte, Quadra 702, Brasília');

INSERT INTO AGENCIA VALUES
(341, 2001, 'Agência Paulista', 'Avenida Paulista, 1230, São Paulo');

INSERT INTO AGENCIA VALUES
(341, 2002, 'Agência Vila Olímpia', 'Rua das Olimpíadas, 350, São Paulo');

INSERT INTO AGENCIA VALUES
(237, 3001, 'Agência Osasco', 'Rua da Matriz, 234, Osasco');

INSERT INTO AGENCIA VALUES
(237, 3002, 'Agência Alphaville', 'Alameda Rio Negro, 1500, Barueri');

-- =========================================
-- TABELA CONTA_CORRENTE
-- =========================================
CREATE TABLE CONTA_CORRENTE (
    COD_BANCO NUMBER(3) NOT NULL,
    COD_AGENCIA NUMBER(5) NOT NULL,
    NUMERO_CONTA NUMBER(7) NOT NULL,
    DATA_ABERTURA DATE NOT NULL,
    NOME_CORRENTISTA VARCHAR2(60) NOT NULL,
    LIMITE_CHEQUE NUMBER(7,2),

    CONSTRAINT CONTA_CORRENTE_PK
        PRIMARY KEY (COD_BANCO, COD_AGENCIA, NUMERO_CONTA),

    CONSTRAINT CONTA_CORRENTE_BANCO_FK
        FOREIGN KEY (COD_BANCO)
        REFERENCES BANCO(COD_BANCO),

    CONSTRAINT CONTA_CORRENTE_AGENCIA_FK
        FOREIGN KEY (COD_BANCO, COD_AGENCIA)
        REFERENCES AGENCIA(COD_BANCO, COD_AGENCIA)
);

INSERT INTO CONTA_CORRENTE VALUES
(001, 1001, 1234567, TO_DATE('10/01/2020','DD/MM/YYYY'), 'Carlos da Silva', 2000.00);

INSERT INTO CONTA_CORRENTE VALUES
(001, 1002, 7654321, TO_DATE('15/03/2019','DD/MM/YYYY'), 'Maria Oliveira', 3000.00);

INSERT INTO CONTA_CORRENTE VALUES
(341, 2001, 2345678, TO_DATE('20/05/2021','DD/MM/YYYY'), 'João Pereira', 5000.00);

INSERT INTO CONTA_CORRENTE VALUES
(341, 2002, 8765432, TO_DATE('02/02/2022','DD/MM/YYYY'), 'Ana Souza', 2500.00);

INSERT INTO CONTA_CORRENTE VALUES
(237, 3001, 3456789, TO_DATE('08/11/2018','DD/MM/YYYY'), 'Roberto Mendes', 4000.00);

INSERT INTO CONTA_CORRENTE VALUES
(237, 3002, 9876543, TO_DATE('12/07/2020','DD/MM/YYYY'), 'Fernanda Lima', 3500.00);

-- =========================================
-- CONSULTAS
-- =========================================
SELECT * FROM BANCO;
SELECT * FROM AGENCIA;
SELECT * FROM CONTA_CORRENTE;